default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: books_development

test: &test
  <<: *default
  database: books_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: books_production

cucumber:
  <<: *test